function importedData = importBEAMData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  OCT26 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  OCT26 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  oct26 = importfile("C:\Users\VNEL\Dropbox\School\PhD\PhD Work\Codes\MATLAB\Data Analysis\October2023\oct26.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 01-Nov-2023 14:58:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Header", "Right_Eye_X", "Right_Eye_Y", "Left_Eye_X", "Left_Eye_Y", "Time_s"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Header", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Header", "EmptyFieldRule", "auto");

% Import the data
importedData = readtable(filename, opts);

end
